repositories:
  remote:
   - http://repo1.maven.org/maven2

artifacts:
  javax_javaee: javax:javaee-api:jar:7.0
  javax_annotation: com.google.code.findbugs:jsr305:jar:2.0.1
  gwt_user: com.google.gwt:gwt-user:jar:2.5.1
  gwt_dev: com.google.gwt:gwt-dev:jar:2.5.1

  javax_validation: javax.validation:validation-api:jar:1.0.0.GA
  javax_validation_sources: javax.validation:validation-api:jar:sources:1.0.0.GA

  gwt_eventsource: org.realityforge.gwt.eventsource:gwt-eventsource:jar:9411865

  jersey_server: org.glassfish.jersey.core:jersey-server:jar:2.0
  jersey_sse: org.glassfish.jersey.media:jersey-media-sse:jar:2.0
